from pathlib import Path
p=Path('android/app/src/main/kotlin/com/lladlam/melox/ui/player/MeloXIOSLyricsPanel.kt')
s=p.read_text()
old='''    val latestInterfaceHidden = rememberUpdatedState(isInterfaceHidden)\n    val latestAutomaticScroll = rememberUpdatedState(automaticScroll)\n    val latestVisibilityCallback = rememberUpdatedState(onInterfaceVisibilityChange)\n'''
new='''    val latestInterfaceHidden = rememberUpdatedState(isInterfaceHidden)\n    val latestVisibilityCallback = rememberUpdatedState(onInterfaceVisibilityChange)\n'''
if old not in s: raise SystemExit('missing automatic-scroll state block')
s=s.replace(old,new,1)
old='''            override fun onPreScroll(available: Offset, source: NestedScrollSource): Offset {\n                if (source != NestedScrollSource.UserInput || latestAutomaticScroll.value) return Offset.Zero\n                val offsetDelta = -available.y // match SwiftUI contentOffset delta\n                if (kotlin.math.abs(offsetDelta) < 0.01f) return Offset.Zero\n\n                isBrowsingLyrics = true\n                browseGeneration += 1\n                latestInteractionCallback.value.invoke()\n\n                if (offsetDelta < 0f) {\n                    // Scrolling back toward previous lyrics immediately restores UI.\n                    scrollHideDistancePx = 0f\n                    if (latestInterfaceHidden.value) latestVisibilityCallback.value.invoke(true)\n                } else if (!latestInterfaceHidden.value) {\n                    scrollHideDistancePx += offsetDelta\n                    if (scrollHideDistancePx >= scrollHideThresholdPx) {\n                        scrollHideDistancePx = 0f\n                        latestVisibilityCallback.value.invoke(false)\n                    }\n                }\n                return Offset.Zero\n            }\n'''
new='''            override fun onPreScroll(available: Offset, source: NestedScrollSource): Offset {\n                if (source != NestedScrollSource.UserInput) return Offset.Zero\n                val offsetDelta = -available.y // match SwiftUI contentOffset delta\n                if (kotlin.math.abs(offsetDelta) < 0.01f) return Offset.Zero\n\n                isBrowsingLyrics = true\n                browseGeneration += 1\n\n                if (offsetDelta < 0f) {\n                    // Browsing back toward previous lyrics restores controls immediately.\n                    scrollHideDistancePx = 0f\n                    if (latestInterfaceHidden.value) {\n                        latestVisibilityCallback.value.invoke(true)\n                    } else {\n                        latestInteractionCallback.value.invoke()\n                    }\n                } else if (!latestInterfaceHidden.value) {\n                    // Forward browsing keeps an already-hidden interface hidden; if\n                    // controls are visible, activity resets the 5-second idle timer\n                    // and 200dp of continued scrolling hides them, matching upstream.\n                    latestInteractionCallback.value.invoke()\n                    scrollHideDistancePx += offsetDelta\n                    if (scrollHideDistancePx >= scrollHideThresholdPx) {\n                        scrollHideDistancePx = 0f\n                        latestVisibilityCallback.value.invoke(false)\n                    }\n                }\n                return Offset.Zero\n            }\n'''
if old not in s: raise SystemExit('missing nested scroll block')
s=s.replace(old,new,1)
p.write_text(s)
print('lyric gesture handoff corrected')
